name: gameai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip>=23.0
  - setuptools>=45
  - wheel>=0.38.0
  - setuptools_scm>=6.2
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - black>=23.0.0
  - isort>=5.12.0
  - flake8>=6.0.0
  - mypy>=1.0.0
  - opencv>=4.8.0
  - pillow>=10.0.0
  - numpy>=1.24.0
  - flask>=2.0.0
  - pyyaml>=6.0.2
  - psutil>=5.9.0
  - pip:
    - paddlepaddle>=2.5.0
    - paddleocr>=2.7.0
    - pytesseract>=0.3.0
    - tencentcloud-sdk-python>=3.0.0 